export const DOCTORS_LOADED_SUCCESS = 'DOCTORS_LOADED_SUCCESS';
export const DOCTORS_LOADED_ERROR = 'DOCTORS_LOADED_ERROR';
export const API_CALL_BEGAN = 'API_CALL_BEGAN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
